src/Entity/Rental.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use App\Repository\RentalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RentalRepository::class)
 */
class Rental
{
    use TimestampableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Type("\DateTimeInterface")
     * 
     * 
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThanOrEqual(propertyPath="date_start")
     */
    private $date_end;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $km_start;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\GreaterThanOrEqual(propertyPath="km_start")
     * 
     */
    private $km_end;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rentals")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="rentals")
     */
    private $reviews;


    /**
     * @ORM\ManyToOne(targetEntity=Motorcycle::class, inversedBy="rentals")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $motorcycle;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(?\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getKmStart(): ?int
    {
        return $this->km_start;
    }

    public function setKmStart(int $km_start): self
    {
        $this->km_start = $km_start;

        return $this;
    }

    public function getKmEnd(): ?int
    {
        return $this->km_end;
    }

    public function setKmEnd(?int $km_end): self
    {
        $this->km_end = $km_end;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function motorcycledReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRental($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless alremotorcycley changed)
            if ($review->getRental() === $this) {
                $review->setRental(null);
            }
        }

        return $this;
    }

    public function getMotorcycle(): ?Motorcycle
    {
        return $this->motorcycle;
    }

    public function setMotorcycle(?Motorcycle $motorcycle): self
    {
        $this->motorcycle = $motorcycle;

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Form/Rental/RestitutionType.php
<?php

namespace App\Form\Rental;

use App\Entity\Rental;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestitutionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('km_end')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rental::class,
        ]);
    }
}

src/Form/RentalType.php
<?php

namespace App\Form;

use App\Entity\Rental;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RentalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_start', DateTimeType::class, [
                'date_label' => 'Start',
            ])
            ->add('date_end', DateTimeType::class, [
                'date_label' => 'End',
            ])
            ->add('status')
            ->add('km_start')
            ->add('km_end')
            ->add('motorcycle');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rental::class,
        ]);
    }
}

src/Controller/Admin/RentalController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Rental;
use App\Form\NewmessageType;
use App\Form\RentalType;
use App\Form\TriStatusType;
use App\Verification\VerificationAccess;
use App\Form\Rental\RestitutionType;
use App\Repository\RentalRepository;
use App\Repository\MotorcycleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;


#[Route('/', requirements: ['back' => "admin|dashboard"])]
class RentalController extends AbstractController
{
    #[Route('admin/rental/', name: 'admin_rental_index', methods: ['GET','POST'])]
    public function admin_index(RentalRepository $rentalRepository,Request $request): Response
    {
        if (empty($_GET['status'])){
            $status = 0;
        }
        else{
            $status = $_GET['status'];
        }
        // $form = $this->createFormBuilder()->add('status',ChoiceType::class,[
        //     'choices' => [
        //         'Tout' =>0,
        //         'Location Crée' => 1,
        //         'Location Validée par propriétaire' => 2,
        //         'Véhicule remis au locataire' => 3,
        //         'Véhicule restitué' =>4,
        //         'Location Clos' =>5,
        //         'Location SAV' => 6,
        //     ],
        // ])
        // ->getForm();

        $rental= $rentalRepository->findBy([], ["date_start" => "DESC"]);
        // $form->handleRequest($request);

       
            if ($status != 0){
                $rental = $rentalRepository->findBy(['status' => $status], ["date_start" => "DESC"]);
            }
            
        
      
        return $this->render('admin/rental/index.html.twig', [
            'rentals' => $rental,
            'status' => $status,
        ]);
    }

    #[Route('dashboard/rental/', name: 'dashboard_rental_index', methods: ['GET'])]
    public function dashboard_index(RentalRepository $rentalRepository, MotorcycleRepository $motorcycleRepository): Response
    {
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        $mesmotos = $motorcycleRepository->findBy(["user" => $user->getId()]);
        return $this->render('dashboard/rental/index.html.twig', [
            'mesmotos' => $mesmotos,
        ]);
    }

    #[Route('dashboard/reservation/', name: 'dashboard_reservation', methods: ['GET'])]
    public function dashboard_reservation(RentalRepository $rentalRepository): Response
    {

        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        return $this->render('dashboard/rental/reservation.html.twig', [
            'rentals' => $rentalRepository->findBy(["user" => $user->getId()],['createdAt' =>'DESC']),
        ]);
    }


    #[Route('admin/rental/new', name: 'admin_rental_new', methods: ['GET', 'POST'], defaults: ['back' => "admin"])]
    #[Route('dashboard/rental/new', name: 'dashboard_rental_new', methods: ['GET', 'POST'], defaults: ['back' => "dashboard"])]
    public function new(Request $request, EntityManagerInterface $entityManager, $back): Response
    {
        $rental = new Rental();
        $form = $this->createForm(RentalType::class, $rental);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var \App\Entity\User $user */
            $user = $this->getUser();
            $rental->setUser($user);
            $entityManager->persist($rental);
            $entityManager->flush();

            return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm("{$back}/rental/new.html.twig", [
            'rental' => $rental,
            'form' => $form,
        ]);
    }

    #[Route('admin/rental/{id}', name: 'admin_rental_show', methods: ['GET'], defaults: ['back' => "admin"])]
    #[Route('dashboard/rental/{id}', name: 'dashboard_rental_show', methods: ['GET'], defaults: ['back' => "dashboard"])]
    public function show(Rental $rental, $back): Response
    {
        if($back == "dashboard")
        {
            /** @var User $user */
            $user = $this->getUser()->getId();
            if($rental->getUser()->getId() != $user && $rental->getMotorcycle()->getUser()->getId() != $user)
            {
                
                throw new AccessDeniedException("Vous n'avez pas l'accès !! ");
            }
        }
        return $this->render("{$back}/rental/show.html.twig", [
            'rental' => $rental,
        ]);
    }

    #[Route('admin/rental/{id}/edit', name: 'admin_rental_edit', methods: ['GET', 'POST'], defaults: ['back' => "admin"])]
    public function edit(Request $request, Rental $rental, EntityManagerInterface $entityManager, $back): Response
    {
        $form = $this->createForm(RentalType::class, $rental);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm("{$back}/rental/edit.html.twig", [
            'rental' => $rental,
            'form' => $form,
        ]);
    }

    #[Route('admin/rental/{id}', name: 'admin_rental_delete', methods: ['POST'], defaults: ['back' => "admin"])]
    #[Route('dashboard/rental/{id}', name: 'dashboard_rental_delete', methods: ['POST'], defaults: ['back' => "dashboard"])]
    public function delete(Request $request, Rental $rental, EntityManagerInterface $entityManager, $back): Response
    {
        if ($this->isCsrfTokenValid('delete' . $rental->getId(), $request->request->get('_token'))) {
            if ($back =="dashboard")
            {
                $rental->setStatus(7);
                $entityManager->flush();
                return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
            }
            $entityManager->remove($rental);
            $entityManager->flush();
        }

        return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
    }

    #[Route('dashboard/rental/validation-reservation/{id}', name: 'dashboard_valider_reservation', methods: ['GET'], defaults: ['back' => "dashboard"])]
    #[Route('admin/rental/validation-reservation/{id}', name: 'valider_reservation', methods: ['GET'], defaults: ['back' => "admin"])]
    public function validation_reservation(Request $request, Rental $rental, EntityManagerInterface $entityManager, $back,VerificationAccess $verification){

        if($back == "dashboard")
        {
            $verification->Verification_edit_moto($rental->getMotorcycle()->getUser()->getId(),$this->getUser());
            if($rental->getStatus() != 1){
                throw new AccessDeniedException("Vous n avez pas l accès !!!");
            }
        }
        $rental->setStatus(2);
        $entityManager->flush();
        return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
    }

    #[Route('dashboard/rental/remis-client/{id}', name: 'dashboard_remis_client', methods: ['GET'], defaults: ['back' => "dashboard"])]
    #[Route('admin/rental/remis-client/{id}', name: 'remis_client', methods: ['GET'], defaults: ['back' => "admin"])]
    public function remis_client(Request $request, Rental $rental, EntityManagerInterface $entityManager, $back,VerificationAccess $verification){
        if($back == "dashboard")
        {
            $verification->Verification_edit_moto($rental->getMotorcycle()->getUser()->getId(),$this->getUser());
            if($rental->getStatus() != 2){
                throw new AccessDeniedException("Vous n avez pas l accès !!");
            }
            if($rental->getDateStart()->format('Y-m-d') != date('Y-m-d'))
            {
                $this->addFlash('error',"La date de location n'a pas comencé ! Veuillé contacter l'Administrateur en cas de probleme. ");
                return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
            }
        }
        $rental->setStatus(3);
        $rental->getMotorcycle()->setStatus(2);
        $entityManager->flush();
        $this->addFlash('message',"Le véhicule a été remis au client.");
        return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
    }

    #[Route('admin/rental/restitution/{id}', name: 'admin_restitution', methods: ['GET','POST'], defaults: ['back' => "admin"])]
    #[Route('dashboard/rental/restitution/{id}', name: 'dashboard_restitution', methods: ['GET','POST'], defaults: ['back' => "dashboard"])]
    public function restitution(Request $request, Rental $rental, EntityManagerInterface $entityManager, $back,VerificationAccess $verification): Response
    {
        if($back == "dashboard")
        {
            $verification->Verification_edit_moto($rental->getMotorcycle()->getUser()->getId(),$this->getUser());
            if($rental->getStatus() != 3){
                throw new AccessDeniedException("Vous n avez pas l accès !!!");
            }
        }
        $form = $this->createForm(RestitutionType::class, $rental);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rental->setStatus(4);
            $rental->getMotorcycle()->setKm($form->get('km_end')->getData());
            $rental->setDateEnd(new \DateTime('now'));
            $entityManager->flush();

            $this->addFlash('message',"Le véhicule a été restituer, Veuillé vérifier la moto s'il n'y a pas de problème. Vous pouvez cloturer la location.");
            return $this->redirectToRoute("{$back}_rental_index", [], Response::HTTP_SEE_OTHER);
        }

templates/dashboard/rental/_delete_form.html.twig
<form method="post" action="{{ path('dashboard_rental_delete', {'id': rental.id}) }}" onsubmit="return confirm('Etes vous sure de annuler cette réservation ?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rental.id) }}">
	<button class="btn">
		<i class="bi bi-archive-fill icon-delete"></i>
	</button>
</form>

templates/dashboard/rental/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/dashboard/rental/index.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Rental index
{% endblock %}

{% block body %}
    <h1>Mes Locations</h1>
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('message') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% for mamoto in mesmotos %}

        {% for rental in mamoto.rentals %}
            <div class="d-flex align-items-start border border-2 rounded-3 border-secondary p-3 mb-3 gap-3">
                <div>
                    {% if rental.motorcycle.motorcycleImages|length > 0 %}
                        {# <img src="/images/motorcycles/{{motorcycle.motorcycleImages.first.imageName}}" alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/> #}
                        <img src="{{ vich_uploader_asset(rental.motorcycle.motorcycleImages.first, 'imageFile') }}"
                             height="80px"
                             style="max-height: 80px"
                             class="img-fluid"
                             alt="{{ rental.motorcycle.motorcycleImages.first.imageName }}"/>
                    {% else %}
                        <img src="{{ asset(constant('DEFAULT_IMAGE', rental.motorcycle)) }}"
                             height="80px"
                             style="max-height: 80px"
                             class="card-img-top img-fluid"/>
                    {% endif %}
                </div>
                <div class="flex-grow-1">
                    <h3 class="h4">{{ rental.motorcycle.model.brand.name }} {{ rental.motorcycle.model.name }}</h3>
                    <div class="d-flex align-items-start gap-4">
                        {% set difference = date(rental.dateEnd).diff(date(rental.dateStart)) %}
                        {% set leftDays = difference.days %}
                        {% if leftDays == 0 %}
                            {% set leftDays = 1 %}
                        {% endif %}
                        <div>
                            <span class="h5">{{ leftDays*rental.price }}€</span>
                            <small>({{ leftDays }}J)</small>
                        </div>
                        <div>
                            <span class="h5 mb-0">Locataire</span>
                            <div class="text-secondary">
                                <span>{{ rental.user.lastname }}</span>
                                <span>{{ rental.user.firstname }}</span>
                            </div>
                        </div>
                        <div>
                            {% if rental.kmEnd %}
                                {% set totalKm = rental.kmEnd - rental.kmStart %}
                                <span class="h5 mb-0">{{ totalKm }}km</span>
                                <div class="text-secondary">
                                    <span>{{ rental.kmStart }}km</span>
                                    <span>{{ rental.kmEnd }}km</span>
                                </div>
                            {% endif %}
                        </div>
                        <div>
                            <div class="d-flex align-items-center h5 mb-0">
                                <span>{{ rental.dateStart ? rental.dateStart|date('Y-m-d ') : '' }}</span>
                                <span>➡</span>
                                <span>{{ rental.dateEnd ? rental.dateEnd|date('Y-m-d ') : '' }}</span>
                            </div>
                            <small class="text-secondary">
                                {{ rental.createdAt ? rental.createdAt|date('Y-m-d ') : '' }}
                            </small>
                        </div>
                        <div class="d-flex flex-column flex-grow-1 justify-content-start align-items-end gap-1">
                            {% if rental.status == 1 %}
                                <span class="badge bg-warning">En attente Validation</span>
                            {% endif %}
                            {% if rental.status == 2 %}
                                <span class="badge bg-success">Validé</span>
                            {% endif %}
                            {% if rental.status == 3 %}
                                <span class="badge bg-info">Véhicule remis au client</span>
                            {% endif %}
                            {% if rental.status == 4 %}
                                <span class="badge bg-info">Vehicule Réstitué</span>
                            {% endif %}
                            {% if rental.status == 5 %}
                                <span class="badge bg-dark">Location Clos</span>
                            {% endif %}
                            {% if rental.status == 6 %}
                                <span class="badge bg-danger">SAV</span>
                            {% endif %}
                            {% if rental.status == 7 %}
                                <span class="badge bg-danger">Location Annulée</span>
                            {% endif %}

                            <div>
                                {% if rental.status == 1 %}
                                    <a class="btn btn-success btn-sm"
                                       href=" {{ path('dashboard_valider_reservation', {'id': rental.id}) }} ">
                                        Valider la révervation
                                    </a>
                                {% endif %}
                                {% if rental.status == 2 %}
                                    <a class="btn btn-info btn-sm"
                                       href=" {{ path('dashboard_remis_client', {'id': rental.id}) }} ">
                                        Remis au client
                                    </a>
                                {% endif %}
                                {% if rental.status == 3 %}
                                    <a class="btn btn-info btn-sm" href="{{ path('dashboard_restitution', {'id': rental.id}) }}">
                                        Restitution
                                    </a>
                                {% endif %}
                                {% if rental.status == 4 %}
                                    <a class="btn btn-danger btn-sm"
                                       href="{{ path('dashboard_cloturation', {'id': rental.id}) }}">
                                        Cloturer la location
                                    </a>
                                {% endif %}
                                {% if rental.status == 5 %}
                                    <a class="btn btn-secondary btn-sm"
                                       href=" {{ path('dashboard_sav', {'id': rental.id}) }} ">SAV</a>
                                {% endif %}
                                {% if rental.status == 6 %}
                                    <a class="btn btn-dark btn-sm"
                                       href=" {{ path('dashboard_cloturation', {'id': rental.id}) }} ">
                                        Cloturation SAV
                                    </a>
                                {% endif %}
                            </div>
                            <div class="d-flex align-items-center">
                                <a href="{{ path('dashboard_rental_show', {'id': rental.id}) }}">
                                    <i class="bi bi-eye-fill icon-show"></i>
                                </a>
                                {% if rental.status<3 %}
                                    {{ include('dashboard/rental/_delete_form.html.twig') }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
{% endblock %}

templates/dashboard/rental/reservation.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Rental index
{% endblock %}

{% block body %}
    <h1>Mes Réservations</h1>
    {% for rental in rentals %}
        <div class="d-flex align-items-start border border-2 rounded-3 border-secondary p-3 mb-3 gap-3">
            <div>
                {% if rental.motorcycle.motorcycleImages|length > 0 %}
                    {# <img src="/images/motorcycles/{{motorcycle.motorcycleImages.first.imageName}}" alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/> #}
                    <img src="{{ vich_uploader_asset(rental.motorcycle.motorcycleImages.first, 'imageFile') }}"
                         height="80px"
                         style="max-height: 80px"
                         class="img-fluid"
                         alt="{{ rental.motorcycle.motorcycleImages.first.imageName }}"/>
                {% else %}
                    <img src="{{ asset(constant('DEFAULT_IMAGE', rental.motorcycle)) }}"
                         height="80px"
                         style="max-height: 80px"
                         class="card-img-top img-fluid"/>
                {% endif %}
            </div>
            <div class="flex-grow-1">
                <h3 class="h4">{{ rental.motorcycle.model.brand.name }} {{ rental.motorcycle.model.name }}</h3>
                <div class="d-flex align-items-start gap-4">
                    {% set difference = date(rental.dateEnd).diff(date(rental.dateStart)) %}
                    {% set leftDays = difference.days %}
                    {% if leftDays == 0 %}
                        {% set leftDays = 1 %}
                    {% endif %}
                    <div>
                        <span class="h5">{{ leftDays*rental.price }}€</span>
                        <small>({{ leftDays }}J)</small>
                    </div>
                    {% if rental.kmEnd %}
                        <div>
                            {% set totalKm = rental.kmEnd - rental.kmStart %}
                            <span class="h5 mb-0">{{ totalKm }}km</span>
                            <div class="text-secondary">
                                <span>{{ rental.kmStart }}km</span>
                                <span>{{ rental.kmEnd }}km</span>
                            </div>
                        </div>
                    {% endif %}
                    <div>
                        <div class="d-flex align-items-center h5 mb-0">
                            <span>{{ rental.dateStart ? rental.dateStart|date('Y-m-d ') : '' }}</span>
                            <span>➡</span>
                            <span>{{ rental.dateEnd ? rental.dateEnd|date('Y-m-d ') : '' }}</span>
                        </div>
                        <small class="text-secondary">
                            {{ rental.createdAt ? rental.createdAt|date('Y-m-d ') : '' }}
                        </small>
                    </div>
                    <div class="d-flex flex-column flex-grow-1 justify-content-start align-items-end gap-1">
                        {% if rental.status == 1 %}
                            <span class="badge bg-warning">En attente Validation</span>
                        {% endif %}
                        {% if rental.status == 2 %}
                            <span class="badge bg-success">Validé</span>
                        {% endif %}
                        {% if rental.status == 3 %}
                            <span class="badge bg-info">Véhicule remis au client</span>
                        {% endif %}
                        {% if rental.status == 4 %}
                            <span class="badge bg-info">Vehicule Réstitué</span>
                        {% endif %}
                        {% if rental.status == 5 %}
                            <span class="badge bg-dark">Location Clos</span>
                        {% endif %}
                        {% if rental.status == 6 %}
                            <span class="badge bg-danger">SAV</span>
                        {% endif %}
                        {% if rental.status == 7 %}
                            <span class="badge bg-danger">Réservation Annulée</span>
                        {% endif %}
                        <div>
                            {% if rental.status == 5 %}
                                <a class="btn btn-secondary btn-sm"
                                   href=" {{ path('dashboard_sav', {'id': rental.id}) }} ">SAV</a>
                            {% endif %}
                            {% if rental.status == 6 %}
                                <a class="btn btn-danger btn-sm"
                                   href=" {{ path('dashboard_cloturation', {'id': rental.id}) }} ">
                                    Cloturation SAV
                                </a>
                            {% endif %}
                        </div>
                        <div>
                            <a class="btn btn-info btn-sm"
                               href=" {{ path('dashboard_contact_create', {'rental': rental.id}) }} ">
                                Contacter Propriétaire
                            </a>
                        </div>
                        <div class="d-flex align-items-center">
                            <a href="{{ path('dashboard_rental_show', {'id': rental.id}) }}">
                                <i class="bi bi-eye-fill icon-show"></i>
                            </a>
                            {% if rental.status<3 %}
                                {{ include('dashboard/rental/_delete_form.html.twig') }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/dashboard/rental/show.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Rental
{% endblock %}

{% block body %}
	<h1>Rental</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Date de création</th>
				<td>{{ rental.createdAt ? rental.createdAt|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Date_start</th>
				<td>{{ rental.dateStart ? rental.dateStart|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Date_end</th>
				<td>{{ rental.dateEnd ? rental.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Status</th>
				<td>{{ rental.status }}</td>
			</tr>
			<tr>
				<th>Km_start</th>
				<td>{{ rental.kmStart }}</td>
			</tr>
			<tr>
				<th>Km_end</th>
				<td>{{ rental.kmEnd }}</td>
			</tr>
			<tr>
				<th>Montant</th>
				<td>{{ rental.price }}€</td>
			</tr>
			<tr>
				<th>Jour Location</th>
				{% set difference = date(rental.dateEnd).diff(date(rental.dateStart)) %}
				{% set leftDays = difference.days %}
				{% if leftDays == 0 %}
					{% set leftDays = 1 %}
				{% endif %}
				<td> {{ leftDays }}Jour </td>

			</tr>
		</tbody>
	</table>

	<a href="{{ path('dashboard_rental_index') }}">back to list</a><a href="{{ path('dashboard_contact_create',{'rental': rental.id}) }}">Contacter Le Propriétaire</a>


{% endblock %}