src/Entity/Motorcycle.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use App\Repository\MotorcycleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=MotorcycleRepository::class)
 * @UniqueEntity(
 *     fields={"numberplate"},
 *     message="NumberPlate is already use!"
 * )
 */
class Motorcycle
{
    use TimestampableTrait;

    const DEFAULT_IMAGE = "images/no-image.png";

    const STATUS_HIDDEN = 0;
    const STATUS_AVAILABLE = 1;
    const STATUS_NOT_AVAILABLE = 2;

    // const STATUS = [
    //     self::STATUS_HIDDEN => "Hidden",
    //     self::STATUS_AVAILABLE => "Available",
    //     self::STATUS_NOT_AVAILABLE => "Not Available"
    // ];
    const STATUS = [
        self::STATUS_HIDDEN,
        self::STATUS_AVAILABLE,
        self::STATUS_NOT_AVAILABLE
    ];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $power;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank
     */
    private $numberplate;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $km;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $year;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Choice(choices=self::STATUS, message="Choose a valid status.")
     */
    private $status = self::STATUS_AVAILABLE;

    /**
     * @var string|null
     *^M
     * @Gedmo\Slug(fields={"name", "id"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=LicenceType::class, inversedBy="motorcycles")
     */
    private $licenceType;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="motorcycles")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Model::class, inversedBy="motorcycles")
     */
    private $model;

    /**
     * @ORM\OneToMany(targetEntity=MotorcycleImage::class, mappedBy="motorcycle",cascade={"persist","remove"},orphanRemoval=true)
     */
    private $motorcycleImages;

    /**
     * @ORM\OneToMany(targetEntity=Rental::class, mappedBy="motorcycle")
     */
    private $rentals;

    /**
     * @ORM\Column(type="integer")
     */
    private $Cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $City;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Localisation;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="decimal", precision=12, scale=10, nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="decimal", precision=12, scale=10, nullable=true)
     */
    private $lon;


    public function __construct()
    {
        $this->motorcycleImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPower(): ?int
    {
        return $this->power;
    }

    public function setPower(int $power): self
    {
        $this->power = $power;

        return $this;
    }

    public function getNumberplate(): ?string
    {
        return $this->numberplate;
    }

    public function setNumberplate(string $numberplate): self
    {
        $this->numberplate = $numberplate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function getLicenceType(): ?LicenceType
    {
        return $this->licenceType;
    }

    public function setLicenceType(?LicenceType $licenceType): self
    {
        $this->licenceType = $licenceType;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): self
    {
        $this->model = $model;

        return $this;
    }


    /**
     * @return Collection|MotorcycleImage[]
     */
    public function getMotorcycleImages(): Collection
    {
        return $this->motorcycleImages;
    }

    public function addMotorcycleImage(MotorcycleImage $motorcycleImage): self
    {
        if (!$this->motorcycleImages->contains($motorcycleImage)) {
            $this->motorcycleImages[] = $motorcycleImage;
            $motorcycleImage->setMotorcycle($this);
        }

        return $this;
    }

    public function removeMotorcycleImage(MotorcycleImage $motorcycleImage): self
    {
        if ($this->motorcycleImages->removeElement($motorcycleImage)) {
            // set the owning side to null (unless already changed)
            if ($motorcycleImage->getMotorcycle() === $this) {
                $motorcycleImage->setMotorcycle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Rental[]
     */
    public function getRentals(): Collection
    {
        return $this->rentals;
    }

    public function addRental(Rental $rental): self
    {
        if (!$this->rentals->contains($rental)) {
            $this->rentals[] = $rental;
            $rental->setMotorcycle($this);
        }

        return $this;
    }

    public function removeRental(Rental $rental): self
    {
        if ($this->rentals->removeElement($rental)) {
            // set the owning side to null (unless already changed)
            if ($rental->getMotorcycle() === $this) {
                $rental->setMotorcycle(null);
            }
        }

        return $this;
    }


    public function isHidden()
    {
        return $this->status == self::STATUS_HIDDEN;
    }
    public function isAvalaible()
    {
        return $this->status == self::STATUS_AVAILABLE;
    }
    public function isNotAvalaible()
    {
        return $this->status == self::STATUS_NOT_AVAILABLE;
    }

    // public function __toString()
    // {
        
    //     return $this->name;
    
        
    // }

    public function getCp(): ?int
    {
        return $this->Cp;
    }

    public function setCp(int $Cp): self
    {
        $this->Cp = $Cp;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(string $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(?string $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLon(): ?string
    {
        return $this->lon;
    }

    public function setLon(?string $lon): self
    {
        $this->lon = $lon;

        return $this;
    }
}

src/Form/MotorcycleType.php
<?php

namespace App\Form;

use App\Entity\Model;
use App\Entity\Motorcycle;
use Doctrine\ORM\EntityRepository;
use App\Repository\BrandRepository;
use Symfony\Component\Validator\Constraints;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class MotorcycleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('motorcycle_images', CollectionType::class, [
                'entry_type' => MotorcycleImageType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
                'label' => false,
                'delete_empty' => true,
                'by_reference' => false,
            ])
            ->add('name',null,[
                'label' => "Titre de l'annonce"
            ])
            ->add('power',null,[
                'attr' =>["min" => 10],
            ])
            ->add('price',null,[
                'attr' =>["min" => 10],
            ])
            ->add('numberplate',null,[
                'constraints'=>[
                    new Constraints\Callback(function($object, ExecutionContextInterface $context){
                        if(preg_match('#[A-Z]{2}-[0-9]{3}-[A-Z]{2}#i',$object)){

                        }
                        else{
                            $context->buildViolation('Respecter Format AA-111-BB')->addViolation();

                        }
                    }),
                ]
            ])
            ->add('description')
            ->add('km',null,[
                'attr'=>['min'=>0],
            ])
            ->add('year',null,[
                'attr'=>['min'=>1970,'max'=>date("Y")],
            ])
            ->add('licenceType',null,[
                'required'=>true,
            ])
            ->add('model', EntityType::class,[
                'class' => Model::class,
                // 'query_builder' => function(EntityRepository $er)
                // { return $er->createQueryBuilder('model')->join('model.brand','b')->where('b.name = :name')->setParameter('name','Aprilia'); },
                'choices' => $options['group']->getModels(),
                'choice_label' => 'name',
              
            ])
            ->add('Localisation')
            ->add('City')
            ->add('Cp',null,[
                'attr' => ['min' => 0,'max'=>99999],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Motorcycle::class,
            'group' => null,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'block_motorcycle';
    }
}

src/Controller/Dashboard/DefaultController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ProfileType;
use Symfony\Component\Form\FormError;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Security;

class DefaultController extends AbstractController
{
    /**
     * @var Security
     */
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    #[Route('/', name: 'default')]
    public function index(): Response
    {
        /** @var \App\Entity\User $user */
        $user = $this->getUser()->getRoles();
        if( !$this->getUser()->isVerified())
        {
            $this->addFlash('warning', "Vous n'avez pas encore valider votre Email. Vous ne pourez pas mettre en location votre moto ni louer de moto! ");
        }
        return $this->render('dashboard/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }

    #[Route('dashboard/profile', name: 'dashboard_profile', methods: ['GET', 'POST'])]
    public function profile(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasherInterface): Response
    {

        $user = $this->security->getUser();
        // $userId = $user->getId();
        // dd($user);
        // $user = $entityManager->getRepository(User::class)->find($userId);
        $form = $this->createForm(ProfileType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            if ($form->get("plainPassword")->getData() != null) {
                if ($form->get("oldPassword")->getData() != null) {


                    // $hashedOldPassword = $userPasswordHasherInterface->hashPassword(
                    //     $user,
                    //     $form->get('oldPassword')->getData()
                    // );
                    //  $userPasswordHasherInterface->isV

                    if ($userPasswordHasherInterface->isPasswordValid($user, $form->get('oldPassword')->getData())) {
                        $user->setPassword(
                            $userPasswordHasherInterface->hashPassword(
                                $user,
                                $form->get('plainPassword')->getData()
                            )
                        );
                    } else {
                        $form->get('oldPassword')->addError(new FormError("wrong password"));
                        $this->addFlash('error', 'incorrect oldPassword ');
                        return $this->redirectToRoute('dashboard_profile', [], Response::HTTP_SEE_OTHER);
                    }
                } else {
                    $form->get('oldPassword')->addError(new FormError("can't be null"));
                    $this->addFlash('error', 'oldPassword field can\'t be null');
                    return $this->redirectToRoute('dashboard_profile', [], Response::HTTP_SEE_OTHER);
                }
            }
            /** @var \App\Entity\User $user */
            $entityManager->flush();
            $this->addFlash('success', 'Profile updated successfully');
            return $this->redirectToRoute('dashboard_profile', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('dashboard/profile/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
}

templates/dashboard/motorcycle/_delete_form.html.twig
<form method="post" action="{{ path('dashboard_motorcycle_delete', {'id': motorcycle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ motorcycle.id) }}">
	<button class="btn btn-danger btn-sm" type="submit">Supprimer</button>
</form>

templates/dashboard/motorcycle/_form.html.twig
{# {% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}
{% form_theme form 'dashboard/motorcycle/_form_theme.html.twig' %}
{{ form_start(form) }}

{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}
<style></style>

<div class="row">
	<div class="col">

		{{ form_start(form) }}
		{{ form_errors(form) }}


		<div class="hr-line-dashed"></div>

		<div id="filesProto" data-prototype="{{ form_widget(form.motorcycle_images.vars.prototype)|e }}"></div>

		<div class="row">
			<div class="col col-xs-12" id="filesBox">
				{% set pos = 0 %}
				{% for motorcycle in form.motorcycle_images %}

					<div style="max-width:200px;margin:10px auto">
						<div id="divRemove{{ pos }}" style="display:inline-block;">
							<button type="button" class="btn btn-danger" onclick="removeFile($(this));">
								<i class="fa-solid fa-trash-can" aria-hidden="true"></i>
							</button>
						</div>

						<div id="divPreview{{ pos }}" style=" display:inline-block;">
							<img src="{{ vich_uploader_asset(motorcycle.vars.value, 'imageFile') }}" alt="{{ motorcycle.vars.value.imageName }}" style="max-width:100px"/>
						</div>

						<div style="display:none">
							{{ form_widget(motorcycle) }}
						</div>
					</div>

					{% set pos = pos + 1 %}
				{% endfor %}
			</div>
		</div>
		{{ form_widget(form) }}
		<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
		{{ form_end(form) }}
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
	var fileCount = '{{ form.motorcycle_images|length }}';
var removeButton = "<button type='button' class='btn btn-danger btn-xs' onclick='removeFile($(this));'><i class='fa-solid fa-trash-can' aria-hidden='true'></i></button>";
function removeFile(ob) {
ob.parent().parent().remove();
}
function createAddFile(fileCount) { // grab the prototype template
var newWidget = $("#filesProto").attr('data-prototype');
// replace the "__name__" used in the id and name of the prototype
newWidget = newWidget.replace(/__name__/g, fileCount);
newWidget = "<div style='display:none'>" + newWidget + "</div>";
hideStuff = `<div id='divRemove${fileCount}' style='display: none;'>
	            ${removeButton}
	        </div>
            <div id='divPreview${fileCount}' style='display: inline-block;'>
            </div>
            <div>
				<button type='button' id='jsBtnUpload${fileCount}' class='btn btn-secondary'>
				<i class="fa-solid fa-file-circle-plus"></i> Add Image
				</button>
            </div>`;
$("#filesBox").append("<div style='max-width:200px;margin:10px auto'>" + hideStuff + newWidget + "</div>");

// On click => Simulate file behaviour
$("#jsBtnUpload" + fileCount).on('click', function (e) {
$('#block_motorcycle_motorcycle_images_' + fileCount + '_imageFile_file').trigger('click');
});
// Once the file is added
$('#block_motorcycle_motorcycle_images_' + fileCount + '_imageFile_file').on('change', function () { // Show its name
fileName = $(this).prop('files')[0].name;

const file = $(this).prop('files')[0]

if (file) {
const tagImage = `<img src="${
URL.createObjectURL(file)
}" style="max-width:100px;magin:10px auto"/>`
$("#divPreview" + fileCount).append(tagImage);
}

// $("#divPreview" + fileCount).append(fileName);
// Hide the add file button
$("#jsBtnUpload" + fileCount).hide();
// Show the remove file button
$("#divRemove" + fileCount).show();
$("#divRemove" + fileCount).css('display', 'inline-block');

// Create another instance of add file button and company
createAddFile(parseInt(fileCount) + 1);
});
}


$(document).ready(function () {
createAddFile(fileCount);
fileCount++;
});
</script>

templates/dashboard/motorcycle/demande_location.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Demande de location
{% endblock %}

{% block body %}
	
	<h1>Demande de location </h1>
	{% for message in app.flashes('Success') %}
		<div class="flash-notice">
			{{ message }}
		</div>
	{% endfor %}
	{{ include('dashboard/rental/_form.html.twig') }}

	<a href="{{ path('default') }}">back to list</a>
{% endblock %}

templates/dashboard/motorcycle/edit.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Edit Motorcycle
{% endblock %}

{% block body %}
	<h1>Edit Motorcycle</h1>

	{{ include('dashboard/motorcycle/_form.html.twig', {'button_label': 'Update'}) }}

	<a href="{{ path('dashboard_motorcycle_index') }}">back to list</a>

	{{ include('dashboard/motorcycle/_delete_form.html.twig') }}
{% endblock %}

templates/dashboard/motorcycle/index.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}Mes Motos
{% endblock %}

{% block body %}
    <section class="mb-5">
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('message') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        <h2 class="h3">Motos en cours de vérification</h2>
        {% for motorcycle in unverifiedMotorcycles %}
            <article class="motorcycle map-item-link" data-id="{{ motorcycle.id }}">
                <figure class="motorcycle__figure">
                    {% if motorcycle.motorcycleImages|length > 0 %}
                        {# <img src="/images/motorcycles/{{motorcycle.motorcycleImages.first.imageName}}" alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/> #}
                        <img class="motorcycle__figure__img"
                             src="{{ vich_uploader_asset(motorcycle.motorcycleImages.first, 'imageFile') }}"
                             alt="{{ motorcycle.model }}"/>
                    {% else %}
                        <img class="motorcycle__figure__img"
                             src="{{ asset(constant('DEFAULT_IMAGE', motorcycle)) }}"
                             style="max-width:100px">
                    {% endif %}
                </figure>
                <div class="motorcycle__content">
                    <h1 class="motorcycle__content__title">
                        {{ motorcycle.model.brand.name }} {{ motorcycle.model }}
                    </h1>
                    <small class="motorcycle__content__city">
                        {{ motorcycle.city }}, {{ motorcycle.cp }}
                    </small>
                    <span class="motorcycle__content__license">
                        {{ motorcycle.licenceType.type }}
                    </span>
                </div>
            </article>
        {% endfor %}
    </section>
    <div class="d-flex justify-content-between align-items-start">
        <h2 class="fw-bold">Mes Motos</h2>
        <a class="btn btn-primary" href="{{ path('dashboard_motorcycle_new') }}">Ajouter une moto</a>
    </div>
    <section class="motorcycles">
        {% for motorcycle in motorcycles %}
            {% if motorcycle.status != 3 %}
                <article class="motorcycle motorcycle--status{{motorcycle.status}}" data-id="{{ motorcycle.id }}">
                    <figure class="motorcycle__figure">
                        {% if motorcycle.motorcycleImages|length > 0 %}
                            {# <img src="/images/motorcycles/{{motorcycle.motorcycleImages.first.imageName}}" alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/> #}
                            <img class="motorcycle__figure__img"
                                 src="{{ vich_uploader_asset(motorcycle.motorcycleImages.first, 'imageFile') }}"
                                 alt="{{ motorcycle.model }}"/>
                        {% else %}
                            <img class="motorcycle__figure__img"
                                 src="{{ asset(constant('DEFAULT_IMAGE', motorcycle)) }}"
                                 style="max-width:100px">
                        {% endif %}
                    </figure>
                    <div class="motorcycle__content">
                        <h1 class="motorcycle__content__title">
                            {{ motorcycle.model.brand.name }} {{ motorcycle.model }}
                        </h1>
                        <small class="motorcycle__content__city">
                            {{ motorcycle.city }}, {{ motorcycle.cp }}
                        </small>
                        <span class="motorcycle__content__license">
                            {{ motorcycle.licenceType.type }}
                        </span>
                        <span class="motorcycle__content__price">
                            <strong class="motorcycle__content__price__value">
                                {{ motorcycle.price }}€
                            </strong>
                            <small class="motorcycle__content__price__unit">/jour</small>
                        </span>
                    </div>
                    <div class="motorcycle__actions">
                        <a href="{{ path('dashboard_motorcycle_show', {'id': motorcycle.id}) }}"
                           class="btn btn-dark btn-sm">Fiche de la moto</a>
                        {% if motorcycle.status == 2 or motorcycle.status == 1%}
                            <a href="{{ path('motorcycle_show', {'id': motorcycle.id}) }}"
                               class="btn btn-outline-dark btn-sm">Voir l'annonce</a>
                        {% else %}
                            <a href="#" class="btn btn-outline-dark btn-sm disabled" disabled>Voir l'annonce</a>
                        {% endif %}
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    </section>
    {#<table class="table">
        <thead>
        <tr>
            <th>Photo</th>
            <th>Marque</th>
            <th>Model</th>
            <th>Power</th>
            <th>Numberplate</th>
            <th>Tarif</th>
            <th>Km</th>
            <th>Year</th>
            <th>Status</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for motorcycle in motorcycles %}
            <tr>
                <td>
                    {% if motorcycle.motorcycleImages|length > 0 %}
                        #}{# <img src="/images/motorcycles/{{motorcycle.motorcycleImages.first.imageName}}" alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/> #}{#
                        <img src="{{ vich_uploader_asset(motorcycle.motorcycleImages.first, 'imageFile') }}"
                             alt="{{ motorcycle.motorcycleImages.first.imageName }}" style="max-width:100px"/>
                    {% else %}
                        <img src="{{ asset(constant('DEFAULT_IMAGE', motorcycle)) }}" class="card-img-top"
                             style="max-width:100px">
                    {% endif %}
                </td>
                <td>{{ motorcycle.model.brand.name }}</td>
                <td>{{ motorcycle.model.name }}</td>
                <td>{{ motorcycle.power }}ch</td>
                <td>{{ motorcycle.numberplate }}</td>
                <td>{{ motorcycle.price }}€ /Jour</td>
                <td>{{ motorcycle.km }} km</td>
                <td>{{ motorcycle.year }}</td>
                #}{# {% for rental in motorcycle.rentals %}
						{% if  date() >= rental.date_start && date() <= rental.date_end %}
							<td style="color:red;"> Moto en location </td>
						{% endif %}
					{% endfor %} #}{#
                {% if motorcycle.status == 1 %}
                    <td>
                        <span class="badge text-white bg-success">Disponible</span>
                    </td>
                {% elseif motorcycle.status == 2 %}
                    <td>
                        <span class="badge text-white bg-danger">En location</span>
                    </td>
                {% elseif motorcycle.status == 0 %}
                    <td>
                        <span class="badge text-white bg-warning">En attente</span>
                    </td>
                {% elseif motorcycle.status == 3 %}
                    <td>
                        <span class="badge text-white bg-primary">Annonce supprimée</span>
                    </td>
                {% else %}
                    <td class="fst-italic text-danger">Erreur</td>
                {% endif %}
                <td class="action">
                    <a href="{{ path('dashboard_motorcycle_show', {'id': motorcycle.id}) }}">
                        <i class="bi bi-eye-fill icon-show"></i>
                    </a>
                    {% if motorcycle.status != 2 %}
                        <a href="{{ path('dashboard_motorcycle_edit', {'id': motorcycle.id}) }}">
                            <i class="bi bi-pencil-square icon-edit"></i>
                        </a>
                        {{ include('dashboard/motorcycle/_delete_form.html.twig') }}
                    {% endif %}

                </td>

            </tr>


        {% endfor %}
        </tbody>
    </table>#}



{% endblock %}

templates/dashboard/motorcycle/new.html.twig
{% extends 'base_dashboard.html.twig' %}

{% block title %}easyloc - Ajouter une moto{% endblock %}

{% block body %}
	<h1 class="fw-bold">Ajoutez votre moto</h1>

	{% if motorcycle is not empty %}
		{{ include('dashboard/motorcycle/_form.html.twig') }}
	{% else %}

		<h2>Choisissez la marque de votre moto</h2>
		<div class="list-group">
			{% for brand in brands %}
				<a class="d-flex justify-content-start align-items-center list-group-item list-group-item-action"
				   href="{{ path(back ~ '_motorcycle_new', {'marque' : brand.name}) }}">
					<div style="width: 110px" class="mr-3 d-flex justify-content-center align-items-center">
						<img src="{{ asset(brand.logo) }}" alt="logo marque" height="50px">
					</div>
					<span>{{ brand.name }}</span>
				</a>
			{% endfor %}
		</div>
	{% endif %}


	<div class="my-5">
		<a href="{{ path('dashboard_motorcycle_index') }}">Retour à la liste de vos motos</a>
	</div>
{% endblock %}